repeat_experiment: 3
model: lenet5
dataset: mnist
num_rounds: 100
num_clients: 20
batch_size: 64
num_clients_per_round_fit: 20
num_clients_per_round_eval: 20
proximal_mu: 0.001
aggregation_strategy: FedAvg
seed: 42
config_fit:
  lr: 0.01
  momentum: 0.9
  local_epochs: 2
partitioning:
  non_iid: true
  type: label-skew
  label-skew:
    method: dirichlet
    alpha: 0.2
attacks:
  model_scaling:
    enabled: true
    malicious_client_fraction: 1
    scaling_factor: 0.5

# change affected_stages in model_scaling.py from "fit" to "get_parameters" 
# to run the model initialization attack